### ISSUE TITLE
词嵌入

### ISSUE THREAD

**Issue by zihanxing** [FadedCosine/AIFuture-Multi-Label-Text-Classfication#8]
请问你的词嵌入word embedding是自己实现的还是用的已训练好的预训练模型？

**Comment by FadedCosine** [comment]
BERT的词嵌入是训练好的，我们输入的是一个one-hot vector。

**Comment by ZaaachX** [comment]
谢谢回复！那textCNN呢，本人小白刚入门，确实没看到textCNN的输入层是什么，望不吝赐教

**Comment by FadedCosine** [comment]
textCNN可以输入one-hot vector之后过embedding层去学word embedding，也可以用预训练的word embedding，比如glove等。
